### ISSUE TITLE
Add possibility to request result set in JSON format

### ISSUE THREAD

**Issue by hnaess** [pionl/METno#2]
In additional to XML as resultset, it should be possible to request the data returned as JSON

**Comment by pionl** [comment]
Hi, any requirements on the structure of the JSON?

**Comment by hnaess** [comment]
only JSON data, like this example https://httpbin.org/get
and not JSON package into an XML, like this example: http://openwps.statkart.no/skwms1/wps.elevation?request=Execute&service=WPS&version=1.0.0&identifier=elevationJSON&dataInputs=%5Bgpx%3Dhttp%3A%2F%2Fnorgeskart.no%2Fuser%2Fgpx%2F3bc39939a60bfb608b7ea49207135daa0797866a.gpx%0A%5D

Haven't looked into any details, regarding the format and structure of the JSON result, so I currently don't have anything "meaningful" to contribute with there.

The main purpose is to the utilize the API through making app/widgets for Garmin device using (http://developer.garmin.com/connect-iq/programmers-guide/communication/)

**Comment by pionl** [comment]
@hnaess I've added new pull request (branch feature/json_support), check it if its ok for you. You can run the example.php (echos the json string)

**Comment by hnaess** [comment]
Hi @pionl that was quick. Currently I don't have any environment to test this, but I can set up this later. Can you post/send an example file which I test in the meantime? Will this later be published to http://api.met.no/ ?

**Comment by pionl** [comment]
No sure what do you mean because api.met.no is official API, I've have just created a wrapper to parse the XML data into PHP objects (quite old code so not the best code ever).

You can use this in your own API for your app (just create your own php file that will return the JSON).

Checkout the new branch and open the example.php.
